# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/Demo/Components/index.coffee

module.exports = require './namespace'
.addModules
  App:       require './App'      
  FunButton: require './FunButton'
  Slide:     require './Slide'    
require './Slides'