# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/Demo/Components/namespace.coffee

Demo = require '../namespace'
module.exports = Demo.Components ||
Demo.addNamespace 'Components', class Components extends Neptune.Base
  ;