# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/namespace.coffee

Caffeine = require '../namespace'
module.exports = Caffeine.Script ||
Caffeine.addNamespace 'Script', class Script extends Neptune.Base
  ;