# generated by Neptune Namespaces v1.x.x
# file: Caffeine/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Caffeine ||
Neptune.addNamespace 'Caffeine', class Caffeine extends Neptune.Base
  ;