# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/Demo/Components/Slides/index.coffee

module.exports = require './namespace'
.addModules
  Slide01Logo:                require './Slide01Logo'               
  Slide02Productivity:        require './Slide02Productivity'       
  Slide03Beauty:              require './Slide03Beauty'             
  Slide04Design:              require './Slide04Design'             
  Slide05JsGood:              require './Slide05JsGood'             
  Slide06JsBad:               require './Slide06JsBad'              
  Slide07InternetsVm:         require './Slide07InternetsVm'        
  Slide08Highlights:          require './Slide08Highlights'         
  Slide10Example:             require './Slide10Example'            
  Slide20PoweredByCaffeineMc: require './Slide20PoweredByCaffeineMc'