# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/Demo/Components/Slides/index.coffee

module.exports = require './namespace'
.addModules
  Slide01Logo:         require './Slide01Logo'        
  Slide02Productivity: require './Slide02Productivity'
  Slide03Beauty:       require './Slide03Beauty'      
  Slide04Design:       require './Slide04Design'      
  Slide05Example:      require './Slide05Example'     