# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/Demo/Components/Slides/namespace.coffee

Components = require '../namespace'
module.exports = Components.Slides ||
Components.addNamespace 'Slides', class Slides extends Neptune.Base
  ;