# generated by Neptune Namespaces v3.x.x
# file: Caffeine.Script.Demo/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:       require './App'      
  Button:    require './Button'   
  FunButton: require './FunButton'
  Slide:     require './Slide'    
require './Slides'