// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Script.Demo/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  App:       require('./App'),
  Button:    require('./Button'),
  FunButton: require('./FunButton'),
  Slide:     require('./Slide')
});
require('./Slides');