// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Script.Demo/Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Components',
  class Components extends Neptune.PackageNamespace {}
);
require('./Slides/namespace');