# generated by Neptune Namespaces v3.x.x
# file: Caffeine.Script.Demo/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main:       require './Main'      
  StyleProps: require './StyleProps'
require './Components'