// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Script.Demo/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:       require('./Main'),
  StyleProps: require('./StyleProps')
});
require('./Components');