# generated by Neptune Namespaces v3.x.x
# file: Caffeine.Script.Demo/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Caffeine.Script.Demo', class Demo extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Components/namespace'