// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Script.Demo/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Caffeine.Script.Demo',
  (class Demo extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Components/namespace');