# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/Demo/index.coffee

module.exports = require './namespace'
.addModules
  Main:       require './Main'      
  StyleProps: require './StyleProps'
require './Components'