# generated by Neptune Namespaces v1.x.x
# file: Caffeine/Script/Demo/namespace.coffee

Script = require '../namespace'
module.exports = Script.Demo ||
Script.addNamespace 'Demo', class Demo extends Neptune.Base
  ;