// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Script.Demo/Components/Slides/index.js

(module.exports = require('./namespace'))

.addModules({
  Slide01Logo:                                  require('./Slide01Logo'),
  Slide02Why10ProgrammingIsAwesome:             require('./Slide02-Why-10-ProgrammingIsAwesome'),
  Slide02Why15ProgrammingLetsUs:                require('./Slide02-Why-15-ProgrammingLetsUs'),
  Slide02Why20Productivity:                     require('./Slide02-Why-20-Productivity'),
  Slide02Why30Proof:                            require('./Slide02-Why-30-Proof'),
  Slide02Why40IBelieve:                         require('./Slide02-Why-40-IBelieve'),
  Slide03Design10:                              require('./Slide03-Design-10'),
  Slide03Design20Strategy:                      require('./Slide03-Design-20-Strategy'),
  Slide03Design30RefactorabilityAndReadability: require('./Slide03-Design-30-RefactorabilityAndReadability'),
  Slide04Js10Why:                               require('./Slide04-Js-10-Why'),
  Slide05JsGood:                                require('./Slide05JsGood'),
  Slide06JsBad:                                 require('./Slide06JsBad'),
  Slide07InternetsVm:                           require('./Slide07InternetsVm'),
  Slide08Highlights:                            require('./Slide08Highlights'),
  Slide15Example:                               require('./Slide15Example'),
  Slide20PoweredByCaffeineMc:                   require('./Slide20PoweredByCaffeineMc')
});