# generated by Neptune Namespaces v3.x.x
# file: Caffeine.Script.Demo/Components/Slides/namespace.coffee

module.exports = (require '../namespace').addNamespace('Slides', class Slides extends Neptune.PackageNamespace)
