// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Script.Demo/Components/Slides/namespace.js

module.exports = require('../namespace').addNamespace(
  'Slides',
  class Slides extends Neptune.PackageNamespace {}
);
